### ISSUE TITLE
Missing funcion "GetReflectionFactoryAction"

### ISSUE THREAD

**Issue by famattsson** [TheHedgeify/DagstuhlGAN#5]
Hello!

I am using your GAN for school project, the eventual goal is to run a novel evaluation method on some generated methods. The issue is  that I cannot compile the java code, because there is a file "DagstuhlGAN/marioaiDagstuhl/src/wox/serial/AccessTest" that contains a call to a funciton called "GetReflectionFactoryAction" that seems to be from the "sun.reflect.ReflectionFactory" module. The problem is that there is no such function in said module. Is this a mistake, or do I need a different sun module?

**Comment by famattsson** [comment]
I realized it might be helpful to include the code in question `    private static final ReflectionFactory reflFactory = (ReflectionFactory)
            AccessController.doPrivileged(
                    new ReflectionFactory.GetReflectionFactoryAction());`

**Comment by schrum2** [comment]
I'm well aware of this issue. You are going to have to downgrade your Java version to be able to use this code. I believe the version here should work (Java 8):
https://www.oracle.com/java/technologies/javase/javase-jdk8-downloads.html
