### ISSUE TITLE
Dots are no longer allowed in torch module names

### ISSUE THREAD

**Issue by miguelgondu** [TheHedgeify/DagstuhlGAN#9]
It seems that there was a breaking change in torch, and now they don't allow dots `.` in module names.  [This issue is another example](https://github.com/pytorch/vision/issues/809)

https://github.com/TheHedgeify/DagstuhlGAN/blob/80c3913ef6f8afe07e6c45d4e5843e0336173523/pytorch/models/dcgan.py#L13

The solution is simple: changing the dots for dashes (or any other character). It's already working on my machine, I might create a pull request later today.

**Comment by schrum2** [comment]
I think we actually addressed that in a new branch:
https://github.com/TheHedgeify/DagstuhlGAN/tree/new_pytorch_compatibility
However, we never merged it ... I'm not sure why.

@volnam Could we either merge the compatibility branch, or at least post some kind of prominent message in the README that tells visitors that it exists?
